Quiz_App/config/routes.rb
Rails.application.routes.draw do
  
  get 'questions/new'

  get '/login' => 'sessions#new' 
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/users/new' => 'users#new'
  post '/users/create' => 'users#create'
  get '/users/:id/edit' => 'users#edit'
  delete '/users/:id' => 'users#destroy'
  put '/users/:id' => 'users#update'
  get '/users' => 'users#index'
  get '/users/leaderboard' => 'users#leaderboard'
  
  get '/questions/' => 'questions#index'
  get '/questions/new' => 'questions#new'
  post '/questions/create' => 'questions#create'
  get '/questions/:id/edit' => 'questions#edit'
  #get '/questions/:id' => 'questions#destroy'
  
  get '/play/' => 'play#show'
  post '/play/update' => 'play#update'
  get '/play/complete' => 'play#complete'

  get '/genres/new' => 'genres#new'
  post '/genres/create' => 'genres#create'
  get '/genres/leaderboard' => 'genres#leaderboard'
  #get '/genres/:id' => 'genres#destroy'

  get '/sub_genres/new' => 'sub_genres#new'
  post '/sub_genres/create' => 'sub_genres#create'
  get '/sub_genres/:id' => 'sub_genres#show'

  resources :users, :sessions, :play 
  resources :genres, :subgenres
  resources :questions, :only => [:create, :show, :destroy]

  root to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Quiz_App/app/models/genre.rb
class Genre < ApplicationRecord
end

Quiz_App/app/controllers/genres_controller.rb
class GenresController < ApplicationController
	def new
		@genre=Genre.new
	end

	def show
		@asubgenres=SubGenre.find_by_sql("select * from sub_genres where genreId = " + params[:id].to_s + " and subgenreName in(select subgenreName from leaderboards where userId = " + cur_user.id.to_s + ")")
		@subgenres=SubGenre.find_by_sql("select * from sub_genres where genreId = " + params[:id].to_s + " and subgenreName not in(select subgenreName from leaderboards where userId = " + cur_user.id.to_s + ")")
	end

	def create
		@genre = Genre.new(params.require(:genre).permit(:genreName))
  		if @genre.save
  			@genre.genreId=@genre.id
  			@genre.save
  			redirect_to '/genres/'+@genre.id.to_s
  		else
  			redirect_to "/genres/new"
  		end
	end

	def leaderboard
		@genreName = params[:genreName]
		@subgenreName = params[:subgenreName]
		@leaders=Leaderboard.order("score DESC").all
		#@leaders=@leader.find_by_sql("select * from leaderboards where genreName = '" + params[:genreName] + "' and subgenreName = '" + params[:subgenreName] + "'")
	end

	def destroy
		Genre.find_by(id: params[:id]).destroy
		redirect_to '/users/'
	end
end

Quiz_App/app/helpers/genre_helper.rb
module GenreHelper
end

Quiz_App/app/helpers/genres_helper.rb
module GenresHelper
end

Quiz_App/app/views/genres/leaderboard.html.erb
<h1>
	Leader Board
</h1>

<table class="table table-striped table-hover ">
	<thead>
		<tr>
			<th>
				Genre Name
			</th>
			<th>
				Sub Genre Name
			</th>
			<th>
				Score
			</th>
			<th>
				User Name
			</th>
		</tr>
	</thead>
<% @leaders.each do |i|%>
	<% if @genreName == i.genreName && @subgenreName == i.subgenreName %>
	<tbody>
	<% if i.userId == cur_user.id %>
		<tr class="success">
			<th>
				<%= i.genreName %>
			</th>
			<th>
				<%= i.subgenreName %>
			</th>
			<th>
				<%= i.score %>
			</th>
			<th>
				<%= User.find_by_id(i.userId).name %>
			</th>
		</tr>
	<% else %>
		<tr>
			<th>
				<%= i.genreName %>
			</th>
			<th>
				<%= i.subgenreName %>
			</th>
			<th>
				<%= i.score %>
			</th>
			<th>
				<%= User.find_by_id(i.userId).name %>
			</th>
		</tr>
	<% end %>
	</tbody>
	<% end %>
<% end %>
</table>

Quiz_App/app/views/genres/new.html.erb
<% if cur_user.admin_mode %>
	<div class="row">
  	<div class="col-md-6 col-md-offset-3">
    <%= form_for(:genre, :url => "/genres/create") do |f| %>
      <%= f.label :Genrename %><br/>
      <%= f.text_field :genreName %><br/>

      <%= f.submit "Create a genre", class: "btn btn-primary" %>
    <% end %>
  	</div>
	</div>
<% else %>
	flash[:error]="Access Denied"
<% end %>

Quiz_App/app/views/genres/show.html.erb
<% if !cur_user.admin_mode %>
<p>
	<h1>Name: </h1>
	<%= cur_user.name %>
</p>

<p>
	<h1>Email:</h1>
	<%= cur_user.email %>
</p>

<h1>
	Unattempted Quizzes:
</h1>
	<table class="table table-striped table-hover ">
		<thead>
		<tr>
			<th>Sub_Genre_Name</th>
			<th>Link_To_Quizzes</th>
			<th>Leader Board</th>
		</tr>
		</thead>
		<% @subgenres.each do |i| %>
			<tbody>
			<tr>
				<td><%= i.subgenreName %></td>
				<td><%= link_to 'Play Quiz',play_path(:genreName => params[:genreName] , :subgenreName => i.subgenreName) ,method: :get %></td>
				<td><%= link_to 'LeaderBoard', genres_leaderboard_path(:genreName => params[:genreName] , :subgenreName => i.subgenreName) ,method: :get %></td>
			</tr>
			</tbody>
		<% end %>
	</table>

<h1>
	Attempted Quizzes:
</h1>
	<table class="table table-striped table-hover ">
		<thead>
		<tr>
			<th>Sub_Genre_Name</th>
			<th>Leader Board</th>
		</tr>
		</thead>
		<% @asubgenres.each do |i| %>
			<tbody>
			<tr>
				<td><%= i.subgenreName %></td>
				<td><%= link_to 'LeaderBoard', genres_leaderboard_path(:genreName => params[:genreName] , :subgenreName => i.subgenreName) ,method: :get %></td>
			</tr>
			</tbody>
		<% end %>
	</table>

<% else %>
	<table class="table table-striped table-hover ">
		<thead>
		<tr>
			<th>Sub_Genre_Name</th>
			<th>Link_To_Quizzes_Questions</th>
			<th>Leader Board</th>
		</tr>
		</thead>
		<% @subgenres.each do |i| %>
			<tbody>
			<tr>
				<td><%= i.subgenreName %></td>
				<td><%= link_to 'Questions', questions_path(:genreName => params[:genreName] , :subgenreName => i.subgenreName) ,method: :get %></td>
				<td><%= link_to 'LeaderBoard', genres_leaderboard_path(:genreName => params[:genreName] , :subgenreName => i.subgenreName) ,method: :get %></td>
			</tr>
			</tbody>
		<% end %>
	</table>
<% end %>