Quiz_App/config/routes.rb
Rails.application.routes.draw do
  
  get 'questions/new'

  get '/login' => 'sessions#new' 
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/users/new' => 'users#new'
  post '/users/create' => 'users#create'
  get '/users/:id/edit' => 'users#edit'
  delete '/users/:id' => 'users#destroy'
  put '/users/:id' => 'users#update'
  get '/users' => 'users#index'
  get '/users/leaderboard' => 'users#leaderboard'
  
  get '/questions/' => 'questions#index'
  get '/questions/new' => 'questions#new'
  post '/questions/create' => 'questions#create'
  get '/questions/:id/edit' => 'questions#edit'
  #get '/questions/:id' => 'questions#destroy'
  
  get '/play/' => 'play#show'
  post '/play/update' => 'play#update'
  get '/play/complete' => 'play#complete'

  get '/genres/new' => 'genres#new'
  post '/genres/create' => 'genres#create'
  get '/genres/leaderboard' => 'genres#leaderboard'
  #get '/genres/:id' => 'genres#destroy'

  get '/sub_genres/new' => 'sub_genres#new'
  post '/sub_genres/create' => 'sub_genres#create'
  get '/sub_genres/:id' => 'sub_genres#show'

  resources :users, :sessions, :play 
  resources :genres, :subgenres
  resources :questions, :only => [:create, :show, :destroy]

  root to: 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Quiz_App/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 }, 
  				format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensetive: false}
    has_secure_password
end

Quiz_App/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if cur_user.admin_mode
		  @users=User.all
      @genres=Genre.all
    else
      flash[:error] = 'Access Denied'
    end
  end

  def show
  	@user=User.find(params[:id])
    @genres=Genre.all
  end

  def destroy
    if cur_user.admin_mode
      User.find_by(id: params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to "/users"
    else
      flash[:error]="Access Denied"
    end
  end

  def new
  	@user=User.new
  end

  def edit
    if cur_user.admin_mode
      @user = User.find(params[:id])
    end
  end

  def update
    if cur_user.admin_mode
      @user = User.find(params[:id])
      if @user.update_attributes(params.require(:user).permit(:name,:email,:password,:password_confirmation))
        redirect_to "/users/"
      else
        render 'edit'
      end
    end
  end        

  def create
  	@user = User.new(params.require(:user).permit(:name,:email,:password,:password_confirmation))
  	if @user.save
  		redirect_to '/login'
  	else
  		redirect_to "/users/new"
  	end
  end

  def leaderboard
    @genreName = params[:genreName]
    @leaders = Leaderboard.order("score DESC")
  end
end

Quiz_App/app/helpers/users_helper.rb
module UsersHelper
end

Quiz_App/app/views/users/edit.html.erb
<% if cur_user.admin_mode %>

<h1>Edit User's Profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
      <%= f.label :name %><br/>
      <%= f.text_field :name %><br/>

      <%= f.label :email %><br/>
      <%= f.email_field :email %><br/>

      <%= f.label :password %><br/>
      <%= f.password_field :password %><br/>

      <%= f.label :password_confirmation, "Confirmation" %><br/>
      <%= f.password_field :password_confirmation %><br/>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
      <%= link_to "Cancel", "/users"%>
      <input type="hidden" name="id" value="<%= @user.id %>">
    <% end %>
  </div>
</div>
<% end %>

Quiz_App/app/views/users/index.html.erb
<% if cur_user.admin_mode %><br/>
	You are in ADMIN MODE<br/>
	<h1>
		All Users
	</h1>
	<table class="table table-striped table-hover ">
		<thead>
		<tr>
			<th>
				Name
			</th>
			<th>
				Email
			</th>
			<th>
				Delete
			</th>
			<th>
				Show
			</th>
			<th>
				Edit
			</th>
		</tr>
		</thead>
	<% @users.each do |user| %>
		<tbody>
		<tr>
			<td>
				<%= user.name %>
			</td>
			<td>
				<%= user.email %>
			</td>
			<td>
				<%= link_to 'delete',user_path(:id => user.id), method: :delete, data: { confirm: 'Are you sure?'} %>
			</td>
			<td>
				<%= link_to 'show',user, method: :get %>
			</td>
			<td>
				<%= link_to 'edit',edit_user_path(:id => user.id), method: :get %>
			</td>
		</tr>
		</tbody>
	<% end %>
	</table>
	
	<h1>Quizzes:</h1>
	<table class="table table-striped table-hover ">
		<thead>
		<tr>
			<th>Genre Name</th>
			<th>Link To Subgenre</th>
			<th>Leader Board</th>
			<th>Delete</th>
		</tr>
		</thead>
		<% @genres.each do |i| %>
			<tbody>
			<tr>
				<td><%= i.genreName %></td>
				<td><%= link_to "Go to subgenre",genre_path(:id => i.genreId , :genreName => i.genreName), method: :get %></td>
				<td><%= link_to "LeaderBoard",users_leaderboard_path(:genreName => i.genreName), method: :get %></td>
				<td><%= link_to "Delete", i, method: :delete, data: { confirm: "You sure?" } %></td>
			</tr>
			</tbody>
		<% end %>
		
	</table>
	
	<% else %>
		<p style="color:red">Access Denied</p>
	<% end %>

Quiz_App/app/views/users/leaderboard.html.erb
<h1>
	Leader Board
</h1>

<table class="table table-striped table-hover ">
	<thead>
		<tr>
			<th>
				Genre Name
			</th>
			<th>
				Sub Genre Name
			</th>
			<th>
				Score
			</th>
			<th>
				User Name
			</th>
		</tr>
	</thead>
<% @leaders.each do |i|%>
	<% if @genreName == i.genreName %>
	<tbody>
	<% if i.userId == cur_user.id %>
		<tr class="success">
			<th>
				<%= i.genreName %>
			</th>
			<th>
				<%= i.subgenreName %>
			</th>
			<th>
				<%= i.score %>
			</th>
			<th>
				<%= User.find_by_id(i.userId).name %>
			</th>
		</tr>
	<% else %>
		<tr>
			<th>
				<%= i.genreName %>
			</th>
			<th>
				<%= i.subgenreName %>
			</th>
			<th>
				<%= i.score %>
			</th>
			<th>
				<%= User.find_by_id(i.userId).name %>
			</th>
		</tr>
	<% end %>
	</tbody>
	<% end %>
<% end %>
</table>

Quiz_App/app/views/users/new.html.erb
<div class="sign_up">
<h1>Sign Up</h1>
  
<%#  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
<%#    <%= render 'shared/error_messages' %>
<%#    <p> Name:</br> <%= f.text_field :name %> <%# </p>
    <p> Email:</br> <%= f.text_field :email %> <%#</p>
    <%= f.submit :Signup %>
<%#  <% end %> 
<% if !cur_user %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, :url => "/users/create") do |f| %>
      <%= f.label :name %><br/>
      <%= f.text_field :name %><br/>

      <%= f.label :email %><br/>
      <%= f.email_field :email %><br/>

      <%= f.label :password %><br/>
      <%= f.password_field :password %><br/>

      <%= f.label :password_confirmation, "Confirmation" %><br/>
      <%= f.password_field :password_confirmation %><br/>

      <%= f.submit "Create an account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<% end %>

Quiz_App/app/views/users/show.html.erb
<p>
	<h1>Name: </h1>
	<%= cur_user.name %>
</p>

<p>
	<h1>Email:</h1>
	<%= cur_user.email %>
</p>


<%# if cur_user.admin_mode && @user.admin_mode %>
	<%#= link_to "index","/users", method: :get %>


<% if !@user.admin_mode && !cur_user.admin_mode %>
	<h1>Quizzes:</h1>
	<table class="table table-striped table-hover ">
		<thead>
		<tr>
			<th>Genre Name</th>
			<th>Link To Subgenre</th>
			<th>Leader Board</th>
		</tr>
		</thead>
		<tbody>
		<% @genres.each do |i| %>
			<tr>
				<td><%= i.genreName %></td>
				<td><%= link_to "Go to subgenre",genre_path(:id => i.genreId , :genreName => i.genreName), method: :get %></td>
				<td><%= link_to "LeaderBoard",users_leaderboard_path(:genreName => i.genreName), method: :get %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
<% end %>
<% if cur_user.admin_mode %>
	<h1>
		Selected User Details
	</h1>
	<p>
		<h2>Name: </h2>
		<%= @user.name %>
	</p>

	<p>
		<h2>Email:</h2>
		<%= @user.email %>
	</p>
<% end %>